repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=50000000000000']
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
        files: ^requirements.*\.txt$
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict  # File naming issues
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: fix-encoding-pragma
        args: [--remove]
  - repo: https://github.com/astral-sh/ruff-pre-commit

  # Ruff version.
    rev: v0.11.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

   # Dependencies security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3 # Update me!
    hooks:
      - id: bandit
        args:
        - --quiet
        - --format=custom
        - --configfile=bandit.yaml

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.4.0
    hooks:
    - id: python-safety-dependencies-check
      args: [--short-report, --ignore=42194]

  # Commit message quality
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.5.1
    hooks:
      - id: commitizen
